# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('eye_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=300)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hands',
            fields=[
                ('hand_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=6)),
                ('side_LR', models.CharField(max_length=200)),
                ('wrist_dia', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('leg_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('warrenty', models.IntegerField()),
                ('heel_height', models.IntegerField()),
                ('activity', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=300)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Teeth',
            fields=[
                ('teeth_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=300)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
