# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171003_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='legs',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='legs',
            name='leg_id',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
