# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171019_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legs1',
            old_name='cost',
            new_name='price',
        ),
    ]
