# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171019_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teethdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('Type', models.CharField(max_length=70)),
                ('material', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Teeth',
        ),
        migrations.AlterIndexTogether(
            name='teethdb',
            index_together=set([('id', 'slug')]),
        ),
    ]
