# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171020_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='teethdb',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('name', 'slug')]),
        ),
    ]
