# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171021_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eyedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('color', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Eye',
        ),
        migrations.AlterIndexTogether(
            name='eyedb',
            index_together=set([('id', 'slug')]),
        ),
    ]
