# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171022_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='productdb',
            index_together=set([('id', 'slug')]),
        ),
    ]
