# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(db_index=True, max_length=2000),
        ),
    ]
